name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx8g -XX:+UseG1GC"
  JAVA_VERSION: 25
  ANDROID_API_LEVEL: 36

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v6.0.2

      - name: Configure JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.2
      - run: ./gradlew --version

      - name: Run Ktlint Check On All Sources
        run: ./gradlew ktlintCheck -s

  android:
    name: Android Build
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v6.0.2

      - name: Configure JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.2

      - name: Build Android
        run: ./gradlew :androidApp:assembleDebug :androidApp:testDebugUnitTest -s

  ios:
    name: iOS Build
    needs: lint
    runs-on: macos-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v6.0.2

      - name: Configure JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.2

      - name: Build iOS
        run: ./gradlew :shared:compileKotlinIosArm64 :shared:compileKotlinIosSimulatorArm64 -s

  web:
    name: Web Build
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v6.0.2

      - name: Configure JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.2

      - name: Build Web
        run: ./gradlew :webApp:compileKotlinJs :webApp:compileKotlinWasmJs -s

      - name: Build Web Distribution
        if: github.repository == 'jaredsburrows/kmp-template' && github.ref == 'refs/heads/main'
        run: ./gradlew :webApp:wasmJsBrowserDistribution -s

      - name: Upload Distribution Artifact
        if: github.repository == 'jaredsburrows/kmp-template' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v7.0.0
        with:
          name: wasmjs-dist
          path: webApp/build/dist/wasmJs/productionExecutable/

  publish:
    name: Publish to GitHub Pages
    needs: [ android, ios, web ]
    if: github.repository == 'jaredsburrows/kmp-template' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download Distribution Artifact
        uses: actions/download-artifact@v8.0.0
        with:
          name: wasmjs-dist
          path: dist

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
